site_name: Curso de C++
site_url: https://nifalconi.github.io/curso-cpp/
theme:
  name: material
  language: es
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.mark
  - admonition
  - pymdownx.details
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.18/codemirror.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.18/mode/clike/clike.min.js
  - js/cpprunner.js

copyright: Curso de C++ para principiantes
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.18/codemirror.min.css
  - https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.18/theme/dracula.min.css
  - css/cpprunner.css

nav:
  - Curso de C++:
      - Basico: index.md
      - Medio: medio.md
      - Avanzado: avanzado.md
  - Glosario: glosario.md
  - Estrategias:
      - Como abordar un problema: estrategias.md
  - Referencias:
      - Links utiles: referencias.md
